### ISSUE TITLE
Host maven artifact in a repository like SonaType OSS or Maven Central

### ISSUE THREAD

**Issue by thoutbeckers** [movisens/SmartGattLib#2]
It would much easier to use this library if it was published to to a maven repository.

You can read about how to do that here

http://maven.apache.org/guides/mini/guide-central-repository-upload.html

or here

https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide

If you are interested and need help let me know.

**Comment by JStumpp** [comment]
Added documentation about JitPack repo: ddfd8bdea4f9f7f31f79c6f7184542f5b52ee7d3
