### ISSUE TITLE
Java SE (BlueCove)

### ISSUE THREAD

**Issue by damien-raemy** [movisens/SmartGattLib#4]
Hello,

I would like to use your library to communicate with a Bluetooth LE device using Java SE (Desktop, not mobile), thank to a stack like BlueCove. Do you know if it is possible, and if yes, how?

Thank you,

Damien Raemy,
School of Engineering and Architecture of Fribourg

**Comment by JStumpp** [comment]
Hi,

as far as I know, the BlueCove library has a very poor support for BLE. Additionaly nearly no Desktop has proper driver and hardware to get everything running. If I had to do this, I would use a Blugiga Bluetooth Low Energy USB Dongle (BLED112) and there is also a library available for Java: https://github.com/SINTEF-9012/bglib
It should be easy to use SmartGattLib with the bglib.

Regards,

Jürgen
