### ISSUE TITLE
Cool Project, More Examples?

### ISSUE THREAD

**Issue by cmrockwell** [movisens/SmartGattLib#5]
Hi. This project looks really cool. after looking at the readme and Example.java.
https://github.com/movisens/SmartGattLib/blob/master/src/main/java/com/movisens/smartgattlib/Example.java

I don't quite understand the setup. I'm wondering if you could add a bit more detail to make the usage example complete.

**Comment by mynavy** [comment]
+1 for examples , Great lib !

**Comment by JStumpp** [comment]
Thanks. An example Android project with SmartGattLib is now available [here](https://github.com/movisens/android-SmartGattLib-Example). This is a fork of the Android BluetoothLeGatt Example project. Main modifications can be found in this  [commit](https://github.com/movisens/android-SmartGattLib-Example/commit/7635d950f8af37ddae4a3bf563ddfb658fa88d0f).
