### ISSUE TITLE
BLE Scan and Connection feature missing using Java program

### ISSUE THREAD

**Issue by ashishbhandari** [movisens/SmartGattLib#8]
Is this feature can be implemented using JAVA program which is present for android and ios but not for desktop based app?

1- Scan for devices
2- Connect to a GATT device

BlueCove is a Java library for Bluetooth, for MsWindows, Mac OSX and others.

but it seems that it does not support Bluetooth Low Enegry 4.0.

Android has a standard Java library for Bluetooth LE 4.0: http://developer.android.com/guide/topics/connectivity/bluetooth.html

Is this Java library can be supportable for Bluetooth LE 4.0 for MsWindows and/or Mac OSX?

**Comment by JStumpp** [comment]
Unfortunately there is no common java api for bluetooth low energy. This library is for interpretation of the gatt data. If you are looking for a good ble library for android, try this on in combination with the SmartGattLib: http://polidea.github.io/RxAndroidBle/

**Comment by ashishbhandari** [comment]
thanks for your reply, I am only looking for java api :(

**Comment by IOOOTA** [comment]
actually you may try Intel's [TinyB](https://github.com/intel-iot-devkit/tinyb) library: we find it neat and useful
