### ISSUE TITLE
Send data to ble

### ISSUE THREAD

**Issue by blakazulu** [movisens/SmartGattLib#9]
How can use your code to write data to the ble device?

**Comment by JStumpp** [comment]
The library just provides all UUIDs of the adopted GATT specification and an convenient way to interpret the characteristics (e.g. Heart Rate, BatteryLevel). To read and write data to ble device you need something that can receive/send data like a android library.  You can e.g. use https://github.com/Polidea/RxAndroidBle for that.

**Comment by blakazulu** [comment]
thx
great library by the way
